source 'https://rubygems.org'
ruby '2.3.3'

source 'https://rails-assets.org' do
  gem 'rails-assets-jquery-animatenumber'
  gem 'rails-assets-jquery-circle-progress'
  gem 'rails-assets-jquery-validation'
end

gem 'babel-transpiler'
gem 'devise'
gem 'figaro'
gem 'haml-rails'
gem 'jbuilder', '~> 2.0'
gem 'kaminari'
gem 'omniauth-twitch'
gem 'pg'
gem 'puma'
gem 'pundit'
gem 'rails'
gem 'redis', '~> 3.3'
gem 'rest-client'
gem 'sidekiq'
gem 'sidekiq-cron-tasks'
gem 'sidekiq-failures', '~> 1.0'
gem 'sprockets', '~> 4.0.0.beta5'
gem 'stripe'

gem 'autoprefixer-rails'
gem 'bootstrap', '~> 4.0.0.beta'
gem 'clipboard-rails'
gem 'country_select'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'render_anywhere'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
