source 'https://rubygems.org'
ruby '2.3.3'

gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.0.3'
gem 'redis'
gem 'sidekiq'
gem 'sidekiq-failures', '~> 1.0'
gem 'rest-client'

gem 'autoprefixer-rails'
gem 'bootstrap', '~> 4.0.0.beta'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'rails-assets-jquery-animatenumber', source: 'https://rails-assets.org'
gem 'rails-assets-jquery-circle-progress', source: 'https://rails-assets.org'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.0.5'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
