default: &default
adapter: redis
url: redis://localhost:6379/1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  url: redis://rediscloud:8gjP9W1lV7AXsIZr@redis-12853.c3.eu-west-1-2.ec2.cloud.redislabs.com:12853
